Filesize Checks
NewSpring/Rock-Native pull request #92
Opened 2017-05-31 13:50 UTC by JakeDawkins

**SYS-3764**

# Feature / Fixed Issue(s)
- This **doesn't** check the gzipped filesizes right now. This is just for the AC of the task.
- checks files in `/web/dist/client`. I _think_ that's the right folder.
- right now, it checks all files in the folder the same way

2017-06-01 18:29 UTC, richarddubay commented
My local build files are about the same sizes as the ones that are listed in the danger comment above. So I would _assume_ that this is working correctly.

![](https://media2.giphy.com/media/xT9DPDp0PNRFbuqqli/giphy.gif)

2017-06-05 19:38 UTC, jbaxleyiii commented
@JakeDawkins this is a great start! I'd prefer to see the sizes listed in a table if possible. For instance each file that is over size could get a warning / failure, the name of the file (you can actually even generate a github link to it (I can show you how if you need to), the budget, and the size.

I'd love to get gzip into this PR before we merge it, but if need to do another task for it I'm good with that.

Let me know if you have any questions!

2017-06-05 19:40 UTC, jbaxleyiii requested changes

2017-06-05 19:40 UTC, jbaxleyiii commented on dangerfile.js
> +      `Filesizes are getting large (over ${warnSize / 1000}kb): ${warns.join(", ")}`,
@JakeDawkins for the links you can use https://github.com/NewSpring/Rock-Native/blob/1aefbed9bd96c76a0aa7b3a7fdb0ed5b65fc62b3/dangerfile.js#L8-L15

2017-06-05 19:40 UTC, jbaxleyiii commented on dangerfile.js
> +          size: fs.statSync(`${buildDir}${filename}`).size,
we should gzip these prior to merging this PR

2017-06-05 19:40 UTC, jbaxleyiii commented on dangerfile.js
> +  const warns = over
😍 I love this code

2017-06-06 01:29 UTC, jbaxleyiii approved these changes

2017-06-06 01:39 UTC, jbaxleyiii commented
gzipping setup, but the `client.js` and `vendor.js` files it is finding shouldn't actually exist?

2017-06-06 18:40 UTC, merged