iOS Smoke Test (e2e testing)
NewSpring/Rock-Native pull request #95
Opened 2017-06-04 22:32 UTC by delianides

2017-06-04 22:49 UTC, delianides commented
FYI these tests will probably fail on CI for right now.

2017-06-05 19:34 UTC, richarddubay approved these changes
I got these tests to run locally. Also updated the snapshots. But the smoke tests fail on CI. I guess we'd need some work to make that happen.

2017-06-05 20:21 UTC, jbaxleyiii commented on e2e/firstTest.spec.js
> +    await device.reloadReactNative();
dang all of these globals suck

2017-06-05 20:21 UTC, jbaxleyiii commented on e2e/firstTest.spec.js
> +    await element(by.id('increment')).multiTap(2);
that is awesome

2017-06-05 20:22 UTC, jbaxleyiii requested changes
@delianides since jest won't work currently, can you setup npm scripts for running these tests? Add the needed dev deps like detox?

We should be able to tell jest to ignore these files until that PR for support is done.

Any idea what CI support looks like?

2017-06-05 20:44 UTC, delianides commented
@jbaxleyiii ...and tell jest to ignore the `e2e/` directory?

2017-06-05 20:45 UTC, jbaxleyiii commented
@delianides yep!

2017-06-08 14:43 UTC, JakeDawkins approved these changes
The tests have been moved to `/src/__tests__/e2e`. I changed the `yarn e2e` comment to run `detox build && detox test` and configured jest to ignore all `e2e` matching files/folders

2017-06-12 12:57 UTC, jbaxleyiii approved these changes

2017-06-12 12:57 UTC, merged